version: "3"
services:
  app:
    image: bananamilkshake/parameter-service:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1GB
      restart_policy:
        condition: on-failure
    depends_on:
      - mongo
    ports:
      - "8090:8090"
      - "1898:1898"
    command: "java \
              -Dspring.data.mongodb.uri=mongodb://mongo/parameter
              -Dcom.sun.management.jmxremote
              -Dcom.sun.management.jmxremote.authenticate=false
              -Dcom.sun.management.jmxremote.ssl=false
              -Dcom.sun.management.jmxremote.rmi.port=1898
              -Dcom.sun.management.jmxremote.port=1898
              -Djava.rmi.server.hostname=localhost
              -jar parameter-service.jar"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role   == manager]
    networks:
      - webnet
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - parameter:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
volumes:
  parameter: